stages:          # List of stages for jobs, and their order of execution
  - build

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - iso
  script:
    - pacman -Scc
    - mkarchiso -v -w workdir/ -o out/ . || mkarchiso -v -w workdir/ -o out/ .
    - mv out/* blendOS.iso
    - echo $CI_COMMIT_SHA > version
    - sha256sum blendOS.iso > checksum
  artifacts:
    paths:
      - blendOS.iso
      - version
      - checksum